name: rl
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.9=h7e8bc2b_100_cp313
  - python_abi=3.13=1_cp313
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py313h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - alembic==1.17.2
      - annotated-types==0.7.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - class-resolver==0.7.1
      - click==8.3.1
      - click-default-group==1.2.4
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - docdata==0.0.5
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - gymnasium==1.2.2
      - idna==3.11
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - more-click==0.1.3
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - optuna==4.6.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - protobuf==6.33.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pykeen==1.11.1
      - pyparsing==3.2.5
      - pystow==0.7.11
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentry-sdk==2.46.0
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.44
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensordict==0.10.0
      - threadpoolctl==3.6.0
      - torch==2.9.0+cu130
      - torch-max-mem==0.1.4
      - torch-ppr==0.0.8
      - torchaudio==2.9.0+cu130
      - torchrl==0.10.1
      - torchvision==0.24.0+cu130
      - tqdm==4.67.1
      - triton==3.5.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.23.0
      - zipp==3.23.0
prefix: /home/castellanoontiv/miniconda3/envs/rl
